# 🦠 COVID-19 Data Analysis Project
## Notebook 1: Data Loading & Cleaning

**Author:** Ahmed Mohamed Abdelhady

**Date:** March 2026  
**Dataset:** `covid.csv` — 210 countries, 17 features

---

### 📌 Objectives
1. Load the raw dataset from `data/raw/`
2. Inspect structure, data types, and null values
3. Clean and fix data quality issues
4. Engineer new features (fatality rate, recovery rate, etc.)
5. Export the cleaned dataset to `data/processed/`

---

## 📦 Step 1 — Import Libraries

In [10]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', 20)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

print('✅ Libraries imported successfully!')

✅ Libraries imported successfully!

---
## 📂 Step 2 — Load the Dataset

In [11]:
# Load the raw data from the data/raw/ folder
df = pd.read_csv('../data/raw/covid.csv')

print(f'Dataset shape: {df.shape[0]} rows × {df.shape[1]} columns')
print()
df.head(10)

Dataset shape: 209 rows × 17 columns

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,"331,198,130.00",5032179,NaN,"162,804.00",NaN,"2,576,668.00",NaN,"2,292,707.00","18,296.00","15,194.00",492.00,"63,139,605.00","190,640.00",Americas,USA
1,Brazil,South America,"212,710,692.00",2917562,NaN,"98,644.00",NaN,"2,047,660.00",NaN,"771,258.00","8,318.00","13,716.00",464.00,"13,206,188.00","62,085.00",Americas,BRA
2,India,Asia,"1,381,344,997.00",2025409,NaN,"41,638.00",NaN,"1,377,384.00",NaN,"606,387.00","8,944.00","1,466.00",30.00,"22,149,351.00","16,035.00",South-EastAsia,IND
3,Russia,Europe,"145,940,924.00",871894,NaN,"14,606.00",NaN,"676,357.00",NaN,"180,931.00","2,300.00","5,974.00",100.00,"29,716,907.00","203,623.00",Europe,RUS
4,South Africa,Africa,"59,381,566.00",538184,NaN,"9,604.00",NaN,"387,316.00",NaN,"141,264.00",539.00,"9,063.00",162.00,"3,149,807.00","53,044.00",Africa,ZAF
5,Mexico,North America,"129,066,160.00",462690,"6,590.00","50,517.00",819.00,"308,848.00","4,140.00","103,325.00","3,987.00","3,585.00",391.00,"1,056,915.00","8,189.00",Americas,MEX
6,Peru,South America,"33,016,319.00",455409,NaN,"20,424.00",NaN,"310,337.00",NaN,"124,648.00","1,426.00","13,793.00",619.00,"2,493,429.00","75,521.00",Americas,PER
7,Chile,South America,"19,132,514.00",366671,NaN,"9,889.00",NaN,"340,168.00",NaN,"16,614.00","1,358.00","19,165.00",517.00,"1,760,615.00","92,022.00",Americas,CHL
8,Colombia,South America,"50,936,262.00",357710,NaN,"11,939.00",NaN,"192,355.00",NaN,"153,416.00","1,493.00","7,023.00",234.00,"1,801,835.00","35,374.00",Americas,COL
9,Spain,Europe,"46,756,648.00",354530,NaN,"28,500.00",NaN,NaN,NaN,NaN,617.00,"7,582.00",610.00,"7,064,329.00","151,087.00",Europe,ESP

---
## 🔍 Step 3 — Initial Inspection

In [12]:
# Column names & data types
print('=== Column Names & Data Types ===')
print(df.dtypes)
print()
print(f'Shape: {df.shape}')

=== Column Names & Data Types ===
Country/Region       object
Continent            object
Population          float64
TotalCases            int64
NewCases            float64
TotalDeaths         float64
NewDeaths           float64
TotalRecovered      float64
NewRecovered        float64
ActiveCases         float64
Serious,Critical    float64
Tot Cases/1M pop    float64
Deaths/1M pop       float64
TotalTests          float64
Tests/1M pop        float64
WHO Region           object
iso_alpha            object
dtype: object

Shape: (209, 17)

In [13]:
# Check for missing values
print('=== Missing Values per Column ===')
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
print(missing_df[missing_df['Missing Count'] > 0].sort_values('Missing %', ascending=False))

=== Missing Values per Column ===
                  Missing Count  Missing %
NewDeaths                   206      98.56
NewRecovered                206      98.56
NewCases                    205      98.09
Serious,Critical             87      41.63
WHO Region                   25      11.96
Deaths/1M pop                22      10.53
TotalDeaths                  21      10.05
TotalTests                   18       8.61
Tests/1M pop                 18       8.61
TotalRecovered                4       1.91
ActiveCases                   4       1.91
Continent                     1       0.48
Population                    1       0.48
Tot Cases/1M pop              1       0.48

In [14]:
# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f'Duplicate rows: {duplicates}')

# Check last rows (often summary/total rows)
print('\n=== Last 5 Rows ===')
df.tail(5)

Duplicate rows: 0

=== Last 5 Rows ===

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
204,Montserrat,North America,"4,992.00",13,NaN,1.00,NaN,10.00,NaN,2.00,NaN,"2,604.00",200.00,61.00,"12,220.00",NaN,MSR
205,Caribbean Netherlands,North America,"26,247.00",13,NaN,NaN,NaN,7.00,NaN,6.00,NaN,495.00,NaN,424.00,"16,154.00",NaN,
206,Falkland Islands,South America,"3,489.00",13,NaN,NaN,NaN,13.00,NaN,0.00,NaN,"3,726.00",NaN,"1,816.00","520,493.00",NaN,FLK
207,Vatican City,Europe,801.00,12,NaN,NaN,NaN,12.00,NaN,0.00,NaN,"14,981.00",NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,"598,682.00",10,NaN,1.00,NaN,8.00,NaN,1.00,NaN,17.00,2.00,NaN,NaN,Africa,ESH

In [15]:
# Unique values in categorical columns
print('=== Continents ===')
print(df['Continent'].unique())
print()
print('=== WHO Regions ===')
print(df['WHO Region'].unique())

=== Continents ===
['North America' 'South America' 'Asia' 'Europe' 'Africa'
 'Australia/Oceania' nan]

=== WHO Regions ===
['Americas' 'South-EastAsia' 'Europe' 'Africa' 'EasternMediterranean'
 'WesternPacific' nan]

---
## 🧹 Step 4 — Data Cleaning

In [16]:
# ── 4.1 Strip whitespace from all string columns ──
df.columns = df.columns.str.strip()
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

print('✅ Whitespace stripped from column names and string values.')

✅ Whitespace stripped from column names and string values.

In [17]:
# ── 4.2 Rename columns for easier use ──
df.rename(columns={
    'Country/Region'      : 'Country',
    'TotalCases'          : 'TotalCases',
    'NewCases'            : 'NewCases',
    'TotalDeaths'         : 'TotalDeaths',
    'NewDeaths'           : 'NewDeaths',
    'TotalRecovered'      : 'TotalRecovered',
    'NewRecovered'        : 'NewRecovered',
    'ActiveCases'         : 'ActiveCases',
    'Serious,Critical'    : 'SeriousCritical',
    'Tot Cases/1M pop'    : 'CasesPer1M',
    'Deaths/1M pop'       : 'DeathsPer1M',
    'TotalTests'          : 'TotalTests',
    'Tests/1M pop'        : 'TestsPer1M',
    'WHO Region'          : 'WHORegion'
}, inplace=True)

print('✅ Columns renamed.')
print(df.columns.tolist())

✅ Columns renamed.
['Country', 'Continent', 'Population', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'SeriousCritical', 'CasesPer1M', 'DeathsPer1M', 'TotalTests', 'TestsPer1M', 'WHORegion', 'iso_alpha']

In [18]:
# ── 4.3 Remove invalid/non-country rows ──
# Diamond Princess is a cruise ship, not a country
# Also remove any row where Country is NaN (last blank row)
before = len(df)
df = df[df['Country'].notna()]
df = df[df['Country'] != 'Diamond Princess']
after = len(df)

print(f'✅ Removed {before - after} non-country rows. Remaining: {after} countries.')

✅ Removed 1 non-country rows. Remaining: 208 countries.

In [19]:
# ── 4.4 Fill missing numeric values ──
# For NewCases, NewDeaths, NewRecovered — missing means 0 new cases reported
df['NewCases']     = df['NewCases'].fillna(0)
df['NewDeaths']    = df['NewDeaths'].fillna(0)
df['NewRecovered'] = df['NewRecovered'].fillna(0)

# For SeriousCritical — fill with 0
df['SeriousCritical'] = df['SeriousCritical'].fillna(0)

# For TotalTests & TestsPer1M — fill with median (some countries didn't report)
df['TotalTests']  = df['TotalTests'].fillna(df['TotalTests'].median())
df['TestsPer1M']  = df['TestsPer1M'].fillna(df['TestsPer1M'].median())

# For TotalRecovered, TotalDeaths, ActiveCases — fill with median
for col in ['TotalRecovered', 'TotalDeaths', 'ActiveCases', 'DeathsPer1M', 'CasesPer1M']:
    df[col] = df[col].fillna(df[col].median())

print('✅ Missing numeric values filled.')
print(f'Remaining nulls: {df.isnull().sum().sum()}')

✅ Missing numeric values filled.
Remaining nulls: 24

In [20]:
# ── 4.5 Fill missing categorical values ──
# WHORegion and Continent — fill with 'Unknown'
df['WHORegion']  = df['WHORegion'].fillna('Unknown')
df['Continent']  = df['Continent'].fillna('Unknown')
df['iso_alpha']  = df['iso_alpha'].fillna('Unknown')

print('✅ Categorical missing values filled with "Unknown".')

✅ Categorical missing values filled with "Unknown".

In [21]:
# ── 4.6 Fix data types ──
numeric_cols = [
    'Population', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths',
    'TotalRecovered', 'NewRecovered', 'ActiveCases', 'SeriousCritical',
    'CasesPer1M', 'DeathsPer1M', 'TotalTests', 'TestsPer1M'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

print('✅ Data types fixed to numeric.')
df.dtypes

✅ Data types fixed to numeric.

Country             object
Continent           object
Population         float64
TotalCases           int64
NewCases           float64
TotalDeaths        float64
NewDeaths          float64
TotalRecovered     float64
NewRecovered       float64
ActiveCases        float64
SeriousCritical    float64
CasesPer1M         float64
DeathsPer1M        float64
TotalTests         float64
TestsPer1M         float64
WHORegion           object
iso_alpha           object
dtype: object

---
## 🔧 Step 5 — Feature Engineering

We create new calculated columns that are important for analysis:

In [22]:
# ── 5.1 Case Fatality Rate (CFR) ──
# CFR = (TotalDeaths / TotalCases) × 100
# Measures: what % of confirmed cases resulted in death
df['CaseFatalityRate'] = np.where(
    df['TotalCases'] > 0,
    (df['TotalDeaths'] / df['TotalCases'] * 100).round(2),
    0
)

print('✅ CaseFatalityRate created.')

# ── 5.2 Recovery Rate ──
# RecoveryRate = (TotalRecovered / TotalCases) × 100
df['RecoveryRate'] = np.where(
    df['TotalCases'] > 0,
    (df['TotalRecovered'] / df['TotalCases'] * 100).round(2),
    0
)

print('✅ RecoveryRate created.')

# ── 5.3 Active Case Rate ──
# What % of total cases are still active
df['ActiveCaseRate'] = np.where(
    df['TotalCases'] > 0,
    (df['ActiveCases'] / df['TotalCases'] * 100).round(2),
    0
)

print('✅ ActiveCaseRate created.')

# ── 5.4 Tests per Case ──
# How many tests were done per confirmed case
df['TestsPerCase'] = np.where(
    df['TotalCases'] > 0,
    (df['TotalTests'] / df['TotalCases']).round(2),
    0
)

print('✅ TestsPerCase created.')

✅ CaseFatalityRate created.
✅ RecoveryRate created.
✅ ActiveCaseRate created.
✅ TestsPerCase created.

---
## ✅ Step 6 — Final Check & Summary

In [23]:
print('=== Final Dataset Summary ===')
print(f'Shape     : {df.shape}')
print(f'Countries : {df["Country"].nunique()}')
print(f'Continents: {df["Continent"].nunique()} — {df["Continent"].unique().tolist()}')
print(f'Any nulls : {df.isnull().sum().sum()}')
print()
print('=== Columns ===')
print(df.columns.tolist())

=== Final Dataset Summary ===
Shape     : (208, 21)
Countries : 208
Continents: 6 — ['North America', 'South America', 'Asia', 'Europe', 'Africa', 'Australia/Oceania']
Any nulls : 0

=== Columns ===
['Country', 'Continent', 'Population', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'SeriousCritical', 'CasesPer1M', 'DeathsPer1M', 'TotalTests', 'TestsPer1M', 'WHORegion', 'iso_alpha', 'CaseFatalityRate', 'RecoveryRate', 'ActiveCaseRate', 'TestsPerCase']

In [24]:
# Quick statistical summary of key metrics
key_cols = ['TotalCases', 'TotalDeaths', 'TotalRecovered', 'ActiveCases',
            'CaseFatalityRate', 'RecoveryRate', 'TestsPerCase']
df[key_cols].describe().round(2)

,TotalCases,TotalDeaths,TotalRecovered,ActiveCases,CaseFatalityRate,RecoveryRate,TestsPerCase
count,208.00,208.00,208.00,208.00,208.00,208.00,208.00
mean,"92,156.03","3,439.87","58,068.56","27,282.41",44.87,69.82,203.19
std,"433,583.96","14,759.87","254,919.92","173,391.53",161.81,23.83,"1,224.66"
min,10.00,1.00,7.00,0.00,0.05,0.61,0.03
25%,731.25,28.50,338.50,89.50,1.40,53.72,8.85
50%,"4,544.00",119.00,"2,180.00",900.50,2.70,75.74,26.07
75%,"37,336.75",604.25,"19,835.25","7,115.75",5.22,88.79,89.22
max,"5,032,179.00","162,804.00","2,576,668.00","2,292,707.00",991.67,100.00,"13,570.20"

In [25]:
# Preview the final cleaned dataset
df.head(10)

,Country,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,...,CasesPer1M,DeathsPer1M,TotalTests,TestsPer1M,WHORegion,iso_alpha,CaseFatalityRate,RecoveryRate,ActiveCaseRate,TestsPerCase
0,USA,North America,"331,198,130.00",5032179,0.00,"162,804.00",0.00,"2,576,668.00",0.00,"2,292,707.00",...,"15,194.00",492.00,"63,139,605.00","190,640.00",Americas,USA,3.24,51.20,45.56,12.55
1,Brazil,South America,"212,710,692.00",2917562,0.00,"98,644.00",0.00,"2,047,660.00",0.00,"771,258.00",...,"13,716.00",464.00,"13,206,188.00","62,085.00",Americas,BRA,3.38,70.18,26.44,4.53
2,India,Asia,"1,381,344,997.00",2025409,0.00,"41,638.00",0.00,"1,377,384.00",0.00,"606,387.00",...,"1,466.00",30.00,"22,149,351.00","16,035.00",South-EastAsia,IND,2.06,68.01,29.94,10.94
3,Russia,Europe,"145,940,924.00",871894,0.00,"14,606.00",0.00,"676,357.00",0.00,"180,931.00",...,"5,974.00",100.00,"29,716,907.00","203,623.00",Europe,RUS,1.68,77.57,20.75,34.08
4,South Africa,Africa,"59,381,566.00",538184,0.00,"9,604.00",0.00,"387,316.00",0.00,"141,264.00",...,"9,063.00",162.00,"3,149,807.00","53,044.00",Africa,ZAF,1.78,71.97,26.25,5.85
5,Mexico,North America,"129,066,160.00",462690,"6,590.00","50,517.00",819.00,"308,848.00","4,140.00","103,325.00",...,"3,585.00",391.00,"1,056,915.00","8,189.00",Americas,MEX,10.92,66.75,22.33,2.28
6,Peru,South America,"33,016,319.00",455409,0.00,"20,424.00",0.00,"310,337.00",0.00,"124,648.00",...,"13,793.00",619.00,"2,493,429.00","75,521.00",Americas,PER,4.48,68.14,27.37,5.48
7,Chile,South America,"19,132,514.00",366671,0.00,"9,889.00",0.00,"340,168.00",0.00,"16,614.00",...,"19,165.00",517.00,"1,760,615.00","92,022.00",Americas,CHL,2.70,92.77,4.53,4.80
8,Colombia,South America,"50,936,262.00",357710,0.00,"11,939.00",0.00,"192,355.00",0.00,"153,416.00",...,"7,023.00",234.00,"1,801,835.00","35,374.00",Americas,COL,3.34,53.77,42.89,5.04
9,Spain,Europe,"46,756,648.00",354530,0.00,"28,500.00",0.00,"2,180.00",0.00,900.50,...,"7,582.00",610.00,"7,064,329.00","151,087.00",Europe,ESP,8.04,0.61,0.25,19.93

---
## 💾 Step 7 — Export Cleaned Data

In [26]:
# Save cleaned dataset to data/processed/ — this will be used by all subsequent notebooks
df.to_csv('../data/processed/cleaned_covid.csv', index=False)

print('✅ Cleaned dataset saved as: ../data/processed/cleaned_covid.csv')
print(f'   Final shape: {df.shape}')
print(f'   Total countries: {df["Country"].nunique()}')
print()
print('🎉 Notebook 1 Complete! Next: Open 02_exploratory_data_analysis.ipynb')

✅ Cleaned dataset saved as: ../data/processed/cleaned_covid.csv
   Final shape: (208, 21)
   Total countries: 208

🎉 Notebook 1 Complete! Next: Open 02_exploratory_data_analysis.ipynb

---

## 📋 Summary of Changes Made

| Step | Action | Detail |
|------|--------|--------|
| 4.1 | Stripped whitespace | Column names + string values |
| 4.2 | Renamed columns | Removed spaces & slashes for easier coding |
| 4.3 | Removed invalid rows | Removed 'Diamond Princess' (cruise ship) + blank row |
| 4.4 | Filled numeric nulls | NewCases/Deaths → 0; Tests → median |
| 4.5 | Filled categorical nulls | WHORegion, Continent → 'Unknown' |
| 4.6 | Fixed data types | All numeric columns → float64 |
| 5.1 | New: CaseFatalityRate | Deaths / Cases × 100 |
| 5.2 | New: RecoveryRate | Recovered / Cases × 100 |
| 5.3 | New: ActiveCaseRate | Active / Cases × 100 |
| 5.4 | New: TestsPerCase | Tests / Cases |